services:
  - type: web
    name: f1-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app/index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        value: secreto_f1_super_seguro
